# Generated by Django 2.0.5 on 2018-09-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-created',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=True, related_name='products', to='products.Category'),
        ),
        migrations.AlterIndexTogether(
            name='products',
            index_together={('id',)},
        ),
    ]
